
import re
import functools
@functools.lru_cache(maxsize=2048)
def normalize_vi(text: str, use_tokenize: bool = False) -> str:
    # Basic normalization
    if not isinstance(text, str):
        text = str(text or "")
    text = text.strip().lower()

    # Quick cleanup: normalize punctuation and repeated spaces
    text = re.sub(r"[\t\n\r]+", " ", text)
    text = re.sub(r"[""'”“‘’]+", "", text)
    text = re.sub(r"[\-_=+*/\\]+", " ", text)

    # Helper: replace whole words using word boundaries to avoid substring mistakes
    def replace_words(s: str, mapping: dict) -> str:
        for k, v in mapping.items():
            pattern = r"\b" + re.escape(k) + r"\b"
            s = re.sub(pattern, v, s)
        return s

    # Mapping for common abbreviations / no-diacritic tokens -> corrected forms
    # Expanded vocabulary for Vietnamese sentiment analysis
    nodiac_map = {
        # === Thời gian / Time ===
        "hom": "hôm",
        "hnay": "hôm nay",
        "hn": "hôm nay",
        "hqua": "hôm qua",
        "hq": "hôm qua",
        "ngay mai": "ngày mai",
        "ngaymai": "ngày mai",
        "tuan nay": "tuần này",
        "thang nay": "tháng này",
        "nam nay": "năm nay",
        "luc nao": "lúc nào",
        "bao gio": "bao giờ",
        "khi nao": "khi nào",
        
        # === Cảm xúc tích cực / Positive emotions ===
        "rat": "rất",
        "rat nhieu": "rất nhiều",
        "ratnhieu": "rất nhiều",
        "ratvui": "rất vui",
        "rat vui": "rất vui",
        "vui": "vui",
        "vui ve": "vui vẻ",
        "vuive": "vui vẻ",
        "hanh phuc": "hạnh phúc",
        "hanhphuc": "hạnh phúc",
        "sung suong": "sung sướng",
        "phan khoi": "phấn khởi",
        "tuyet voi": "tuyệt vời",
        "tuyetvoi": "tuyệt vời",
        "tuyet": "tuyệt",
        "tot": "tốt",
        "rat tot": "rất tốt",
        "rattot": "rất tốt",
        "qua tot": "quá tốt",
        "hay": "hay",
        "rat hay": "rất hay",
        "rathay": "rất hay",
        "hay lam": "hay lắm",
        "haylam": "hay lắm",
        "dep": "đẹp",
        "rat dep": "rất đẹp",
        "ratdep": "rất đẹp",
        "dep qua": "đẹp quá",
        "ngon": "ngon",
        "rat ngon": "rất ngon",
        "ratngon": "rất ngon",
        "ngon qua": "ngon quá",
        "thich": "thích",
        "rat thich": "rất thích",
        "ratthich": "rất thích",
        "yeu": "yêu",
        "yeu thich": "yêu thích",
        "yeuthich": "yêu thích",
        "tuyet hao": "tuyệt hảo",
        "xuat sac": "xuất sắc",
        "xuatsac": "xuất sắc",
        "hoan hao": "hoàn hảo",
        "hoanhao": "hoàn hảo",
        "hai long": "hài lòng",
        "hailong": "hài lòng",
        "rat hai long": "rất hài lòng",
        "cam on": "cảm ơn",
        "camon": "cảm ơn",
        "cam on ban": "cảm ơn bạn",
        "camonban": "cảm ơn bạn",
        "cam on nhieu": "cảm ơn nhiều",
        "thank": "cảm ơn",
        "thanks": "cảm ơn",
        "ok": "ok",
        "okie": "ok",
        "okela": "ok",
        "nice": "tuyệt",
        "good": "tốt",
        "great": "tuyệt vời",
        "amazing": "tuyệt vời",
        "perfect": "hoàn hảo",
        "sieu": "siêu",
        "cuc ky": "cực kỳ",
        "cucky": "cực kỳ",
        "vo cung": "vô cùng",
        "vocung": "vô cùng",
        
        # === Cảm xúc tiêu cực / Negative emotions ===
        "buon": "buồn",
        "rat buon": "rất buồn",
        "ratbuon": "rất buồn",
        "buon qua": "buồn quá",
        "that bai": "thất bại",
        "thatbai": "thất bại",
        "that vong": "thất vọng",
        "thatvong": "thất vọng",
        "met moi": "mệt mỏi",
        "metmoi": "mệt mỏi",
        "met": "mệt",
        "met qua": "mệt quá",
        "chan": "chán",
        "chan qua": "chán quá",
        "te": "tệ",
        "rat te": "rất tệ",
        "ratte": "rất tệ",
        "te qua": "tệ quá",
        "te hai": "tệ hại",
        "tehai": "tệ hại",
        "do": "dở",
        "do qua": "dở quá",
        "kem": "kém",
        "rat kem": "rất kém",
        "ratkem": "rất kém",
        "kem chat luong": "kém chất lượng",
        "xau": "xấu",
        "rat xau": "rất xấu",
        "ratxau": "rất xấu",
        "xau qua": "xấu quá",
        "gian": "giận",
        "tuc gian": "tức giận",
        "tucgian": "tức giận",
        "buc minh": "bực mình",
        "bucminh": "bực mình",
        "kho chiu": "khó chịu",
        "khochiu": "khó chịu",
        "so": "sợ",
        "lo lang": "lo lắng",
        "lolang": "lo lắng",
        "stress": "căng thẳng",
        "cang thang": "căng thẳng",
        "cangthang": "căng thẳng",
        "bad": "tệ",
        "terrible": "tệ hại",
        "awful": "kinh khủng",
        "horrible": "kinh hoàng",
        "khong hai long": "không hài lòng",
        "khonghailong": "không hài lòng",
        "khong thich": "không thích",
        "khongthich": "không thích",
        
        # === Trung tính / Neutral ===
        "bt": "bình thường",
        "binh thuong": "bình thường",
        "binhthuong": "bình thường",
        "cung duoc": "cũng được",
        "cungduoc": "cũng được",
        "tam duoc": "tạm được",
        "tamduoc": "tạm được",
        "on dinh": "ổn định",
        "ondinh": "ổn định",
        "on": "ổn",
        "on thoi": "ổn thôi",
        "chap nhan duoc": "chấp nhận được",
        "chapnhanduoc": "chấp nhận được",
        "tam on": "tạm ổn",
        "tamon": "tạm ổn",
        "khong co gi": "không có gì",
        "khong sao": "không sao",
        "khongsao": "không sao",
        
        # === Phủ định / Negation ===
        "khong": "không",
        "ko": "không",
        "k": "không",
        "kg": "không",
        "kh": "không",
        "hok": "không",
        "hem": "không",
        "chua": "chưa",
        "ch": "chưa",
        
        # === Từ nối / Connectors ===
        "va": "và",
        "nhung": "nhưng",
        "ma": "mà",
        "vi": "vì",
        "nen": "nên",
        "de": "để",
        "cho": "cho",
        "voi": "với",
        "cung": "cũng",
        "lai": "lại",
        "nua": "nữa",
        "thi": "thì",
        "neu": "nếu",
        
        # === Đại từ / Pronouns ===
        "toi": "tôi",
        "minh": "mình",
        "ban": "bạn",
        "cau": "cậu",
        "anh": "anh",
        "chi": "chị",
        "em": "em",
        "no": "nó",
        "ho": "họ",
        "chung ta": "chúng ta",
        "chungta": "chúng ta",
        "chung toi": "chúng tôi",
        "chungtoi": "chúng tôi",
        "cac ban": "các bạn",
        "cacban": "các bạn",
        
        # === Dịch vụ / Service terms ===
        "mon an": "món ăn",
        "monan": "món ăn",
        "do an": "đồ ăn",
        "doan": "đồ ăn",
        "nuoc uong": "nước uống",
        "nuocuong": "nước uống",
        "dich vu": "dịch vụ",
        "dichvu": "dịch vụ",
        "san pham": "sản phẩm",
        "sanpham": "sản phẩm",
        "nhan vien": "nhân viên",
        "nhanvien": "nhân viên",
        "thai do": "thái độ",
        "thaido": "thái độ",
        "chat luong": "chất lượng",
        "chatluong": "chất lượng",
        "gia ca": "giá cả",
        "giaca": "giá cả",
        "gia": "giá",
        "re": "rẻ",
        "dat": "đắt",
        "qua dat": "quá đắt",
        "gia dat": "giá đắt",
        "giadat": "giá đắt",
        "gia re": "giá rẻ",
        "giare": "giá rẻ",
        "giao hang": "giao hàng",
        "giaohang": "giao hàng",
        "ship": "giao hàng",
        "shipper": "người giao hàng",
        "dong goi": "đóng gói",
        "donggoi": "đóng gói",
        "bao bi": "bao bì",
        "baobi": "bao bì",
        "cua hang": "cửa hàng",
        "cuahang": "cửa hàng",
        "shop": "cửa hàng",
        "nha hang": "nhà hàng",
        "nhahang": "nhà hàng",
        "quan": "quán",
        "khach san": "khách sạn",
        "khachsan": "khách sạn",
        "hotel": "khách sạn",
        
        # === Trường học / Education ===
        "hoc": "học",
        "di hoc": "đi học",
        "dihoc": "đi học",
        "truong": "trường",
        "lop": "lớp",
        "bai tap": "bài tập",
        "baitap": "bài tập",
        "thi": "thi",
        "kiem tra": "kiểm tra",
        "kiemtra": "kiểm tra",
        "giao vien": "giáo viên",
        "giaovien": "giáo viên",
        "thay": "thầy",
        "co": "cô",
        "sinh vien": "sinh viên",
        "sinhvien": "sinh viên",
        "hoc sinh": "học sinh",
        "hocsinh": "học sinh",
        
        # === Công việc / Work ===
        "cong viec": "công việc",
        "congviec": "công việc",
        "lam viec": "làm việc",
        "lamviec": "làm việc",
        "van phong": "văn phòng",
        "vanphong": "văn phòng",
        "sep": "sếp",
        "dong nghiep": "đồng nghiệp",
        "dongnghiep": "đồng nghiệp",
        "luong": "lương",
        "nghi phep": "nghỉ phép",
        "nghiphep": "nghỉ phép",
        "hop": "họp",
        "du an": "dự án",
        "duan": "dự án",
        "deadline": "hạn chót",
        "meeting": "họp",
        
        # === Thời tiết / Weather ===
        "troi": "trời",
        "thoi tiet": "thời tiết",
        "thoitiet": "thời tiết",
        "nang": "nắng",
        "mua": "mưa",
        "lanh": "lạnh",
        "nong": "nóng",
        "mat": "mát",
        "gio": "gió",
        "bao": "bão",
        
        # === Từ tăng cường / Intensifiers ===
        "qua": "quá",
        "lam": "lắm",
        "cuc": "cực",
        "sieu": "siêu",
        "vo cung": "vô cùng",
        "het suc": "hết sức",
        "hetsuc": "hết sức",
        "that su": "thật sự",
        "thatsu": "thật sự",
        "that": "thật",
        "hon": "hơn",
        "nhat": "nhất",
        
        # === Khác / Others ===
        "dk": "được",
        "dc": "được",
        "duoc": "được",
        "dang": "đang",
        "da": "đã",
        "se": "sẽ",
        "roi": "rồi",
        "r": "rồi",
        "chua": "chưa",
        "chu": "chưa",
        "ah": "à",
        "uh": "ừ",
        "nhe": "nhé",
        "nha": "nha",
        "a": "à",
        "day": "đây",
        "do": "đó",
        "kia": "kia",
        "nay": "này",
        "ay": "ấy",
        "gi": "gì",
        "sao": "sao",
        "the nao": "thế nào",
        "thenao": "thế nào",
        "nhu the nao": "như thế nào",
        "nhuthenao": "như thế nào",
        "biet": "biết",
        "hieu": "hiểu",
        "nghi": "nghĩ",
        "muon": "muốn",
        "can": "cần",
        "phai": "phải",
        "nen": "nên",
        "co the": "có thể",
        "cothe": "có thể",
    }
    # More general typo fixes (including spaced variants)
    # Expanded with more common Vietnamese internet slang and abbreviations
    typo_map = {
        # === Viết tắt phổ biến / Common abbreviations ===
        "rat ": "rất ",
        " hom ": " hôm ",
        " hnay ": " hôm nay ",
        " h nay ": " hôm nay ",
        " hqua ": " hôm qua ",
        " h qua ": " hôm qua ",
        " dc ": " được ",
        " đc ": " được ",
        " ko ": " không ",
        " k ": " không ",
        " kg ": " không ",
        " kh ": " không ",
        " hok ": " không ",
        " hem ": " không ",
        " khong ": " không ",
        " cx ": " cũng ",
        " cg ": " cũng ",
        " vs ": " với ",
        " voi ": " với ",
        " wa ": " quá ",
        " qua ": " quá ",
        " wá ": " quá ",
        " ntn ": " như thế nào ",
        " sao ": " sao ",
        " trc ": " trước ",
        " trc ": " trước ",
        " sau ": " sau ",
        " r ": " rồi ",
        " rl ": " rồi ",
        " rui ": " rồi ",
        " roi ": " rồi ",
        " chs ": " chưa ",
        " ch ": " chưa ",
        " chua ": " chưa ",
        
        # === Tính từ / Adjectives ===
        " tot ": " tốt ",
        " dep ": " đẹp ",
        " xau ": " xấu ",
        " ngon ": " ngon ",
        " dở ": " dở ",
        " do ": " dở ",
        " hay ": " hay ",
        " te ": " tệ ",
        " kem ": " kém ",
        " re ": " rẻ ",
        " dat ": " đắt ",
        " nhanh ": " nhanh ",
        " cham ": " chậm ",
        " lon ": " lớn ",
        " nho ": " nhỏ ",
        " nhieu ": " nhiều ",
        " it ": " ít ",
        " moi ": " mới ",
        " cu ": " cũ ",
        " nong ": " nóng ",
        " lanh ": " lạnh ",
        " mat ": " mát ",
        " sach ": " sạch ",
        " ban ": " bẩn ",
        
        # === Từ cảm xúc / Emotion words ===
        " vui ": " vui ",
        " buon ": " buồn ",
        " gian ": " giận ",
        " so ": " sợ ",
        " lo ": " lo ",
        " met ": " mệt ",
        " chan ": " chán ",
        " thich ": " thích ",
        " yeu ": " yêu ",
        " ghet ": " ghét ",
        
        # === Từ hành động / Action words ===
        " j ": " gì ",
        " gi ": " gì ",
        " lam ": " làm ",
        " dk ": " được ",
        " ms ": " mới ",
        " m ": " mới ",
        " nua ": " nữa ",
        " thi ": " thì ",
        " an ": " ăn ",
        " uong ": " uống ",
        " di ": " đi ",
        " ve ": " về ",
        " den ": " đến ",
        " xem ": " xem ",
        " nghe ": " nghe ",
        " noi ": " nói ",
        " viet ": " viết ",
        " doc ": " đọc ",
        " hoc ": " học ",
        " choi ": " chơi ",
        " ngu ": " ngủ ",
        " day ": " dậy ",
        " mua ": " mua ",
        " ban ": " bán ",
        " tra ": " trả ",
        " gui ": " gửi ",
        " nhan ": " nhận ",
        " cho ": " chờ ",
        " doi ": " đợi ",
        
        # === Từ tăng cường / Intensifiers ===
        " cuc ": " cực ",
        " sieu ": " siêu ",
        " qua ": " quá ",
        " lam ": " lắm ",
        " tuyet ": " tuyệt ",
        " rat ": " rất ",
        " vo cung ": " vô cùng ",
        " het suc ": " hết sức ",
        " that su ": " thật sự ",
        
        # === Cụm từ cảm xúc / Emotion phrases ===
        " that vong ": " thất vọng ",
        " thatvong ": " thất vọng ",
        " hai long ": " hài lòng ",
        " hailong ": " hài lòng ",
        " hanh phuc ": " hạnh phúc ",
        " hanhphuc ": " hạnh phúc ",
        " vui ve ": " vui vẻ ",
        " vuive ": " vui vẻ ",
        " buon ba ": " buồn bã ",
        " buonba ": " buồn bã ",
        " lo lang ": " lo lắng ",
        " lolang ": " lo lắng ",
        " tuc gian ": " tức giận ",
        " tucgian ": " tức giận ",
        " kho chiu ": " khó chịu ",
        " khochiu ": " khó chịu ",
        " cam on ": " cảm ơn ",
        " camon ": " cảm ơn ",
        
        # === Dịch vụ / Service terms ===
        " nhan vien ": " nhân viên ",
        " nhanvien ": " nhân viên ",
        " thai do ": " thái độ ",
        " thaido ": " thái độ ",
        " chat luong ": " chất lượng ",
        " chatluong ": " chất lượng ",
        " san pham ": " sản phẩm ",
        " sanpham ": " sản phẩm ",
        " dich vu ": " dịch vụ ",
        " dichvu ": " dịch vụ ",
        " mon an ": " món ăn ",
        " monan ": " món ăn ",
        " do an ": " đồ ăn ",
        " doan ": " đồ ăn ",
        " nuoc uong ": " nước uống ",
        " nuocuong ": " nước uống ",
        " gia ca ": " giá cả ",
        " giaca ": " giá cả ",
        " giao hang ": " giao hàng ",
        " giaohang ": " giao hàng ",
        " dong goi ": " đóng gói ",
        " donggoi ": " đóng gói ",
        " cua hang ": " cửa hàng ",
        " cuahang ": " cửa hàng ",
        " nha hang ": " nhà hàng ",
        " nhahang ": " nhà hàng ",
        
        # === Trung tính / Neutral ===
        " binh thuong ": " bình thường ",
        " binhthuong ": " bình thường ",
        " bt ": " bình thường ",
        " on dinh ": " ổn định ",
        " ondinh ": " ổn định ",
        " cung duoc ": " cũng được ",
        " cungduoc ": " cũng được ",
        " tam duoc ": " tạm được ",
        " tamduoc ": " tạm được ",
        
        # === Công việc & học tập / Work & study ===
        " cong viec ": " công việc ",
        " congviec ": " công việc ",
        " lam viec ": " làm việc ",
        " lamviec ": " làm việc ",
        " di hoc ": " đi học ",
        " dihoc ": " đi học ",
        " bai tap ": " bài tập ",
        " baitap ": " bài tập ",
        " kiem tra ": " kiểm tra ",
        " kiemtra ": " kiểm tra ",
        
        # === Thời tiết / Weather ===
        " thoi tiet ": " thời tiết ",
        " thoitiet ": " thời tiết ",
        " troi ": " trời ",
        " nang ": " nắng ",
        " mua ": " mưa ",
        
        # === Internet slang / Teen code ===
        " nc ": " nói chuyện ",
        " ns ": " nói ",
        " ik ": " đi ",
        " ak ": " à ",
        " uk ": " ừ ",
        " ng ": " người ",
        " nguoi ": " người ",
        " đok ": " đó ",
        " z ": " vậy ",
        " v ": " vậy ",
        " vl ": " vãi ",
        " vcl ": " vãi ",
        " kq ": " kết quả ",
        " ketqua ": " kết quả ",
        " sp ": " sản phẩm ",
        " nv ": " nhân viên ",
        " dv ": " dịch vụ ",
        " cl ": " chất lượng ",
        " dt ": " điện thoại ",
        " dienthoai ": " điện thoại ",
        " tb ": " trung bình ",
        " trungbinh ": " trung bình ",
    }

    # If text contains no Vietnamese diacritics, apply nodiac_map first
    if not re.search(r"[\u00C0-\u1EF9]", text):
        text = replace_words(text, nodiac_map)

    # Apply general typo corrections
    text = replace_words(text, typo_map)
    
    # Optional: use underthesea for word tokenization
    if use_tokenize:
        try:
            from underthesea import word_tokenize
            text = word_tokenize(text, format="text")
        except ImportError:
            pass  # Skip if underthesea not installed
    
    # Limit length to 200 chars
    text = text[:200]
    
    # Final cleanup
    text = " ".join(text.split())  # Remove extra whitespace

    return text
